import Head from 'next/head'
import Banner from '../components/banner'
import Card from '../components/card'
import styles from '../styles/Home.module.css'
import Image from 'next/image';

import coffeestoresData from '../data/coffee-stores.json';




export async function getStaticProps (context) {
  return {
    props: {
      coffeestores: coffeestoresData,
    },
  }
}

export default function Home(props) {

  console.log(props);

  const handleOnBannerBtnClick = () => {
    console.log("Hi banner button!")
  };


  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner buttonText="View stores nearby" handleOnClick={handleOnBannerBtnClick} />
        <div className={styles.heroImage}>
        <Image src="/static/man1.png" width={700} height={400} />
        </div>
        {props.coffeestores.length > 0 &&
        <div>
        <h2 className={styles.heading2}>Toronto Coffee Stores</h2>
        <div className={styles.cardLayout}>
        {props.coffeestores.map(coffeeStore => {
        return <Card key={coffeeStore.id} className={styles.card} name={coffeeStore.name} imgUrl={coffeeStore.imgUrl}
         href={`/coffee-store/${coffeeStore.id}`} />})}
        </div>
        </div>  
          }
      </main>
    </div>
  )
}
